/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Market descriptor input from Node.js. */
export interface NapiMarketDescriptorInput {
  marketId: string
  slug: string
  clobTokenIds: Array<string>
  boundsLower?: number
  boundsUpper?: number
  kind: string
  negRisk: boolean
}
/** Group input from Node.js. */
export interface NapiRangeGroupInput {
  groupKey: string
  eventSlug: string
  crypto: string
  children: Array<NapiMarketDescriptorInput>
  parents: Array<NapiMarketDescriptorInput>
}
/** Engine config input from Node.js. */
export interface NapiEngineConfigInput {
  minProfitBps?: number
  minProfitAbs?: number
  cooldownMs?: number
}
/** Engine status output. */
export interface NapiEngineStatus {
  totalGroups: number
  totalTrios: number
  totalPriceSlots: number
  totalTokensIndexed: number
}
/**
 * Initialize the Rust socket engine with the given configuration.
 *
 * Must be called before any other socket functions.
 * Creates the internal SocketManager and tokio runtime.
 */
export declare function initSocket(config: SocketConfig): void
/** Subscribe to a list of token IDs. */
export declare function subscribeTokens(tokenIds: Array<string>): void
/** Unsubscribe from a list of token IDs. */
export declare function unsubscribeTokens(tokenIds: Array<string>): void
/** Get the current socket status (connection count, message stats, etc.). */
export declare function getSocketStatus(): SocketStatus
/** Gracefully shutdown the Rust socket engine. */
export declare function shutdownSocket(): void
/**
 * Update the market structure (groups, markets, trios).
 *
 * Called by Node.js when markets are discovered/refreshed.
 * Rebuilds PriceTable, groups, and trio indices.
 * Returns the total number of trios created.
 */
export declare function updateMarketStructure(groups: Array<NapiRangeGroupInput>): number
/** Update engine configuration (profit thresholds, cooldown). */
export declare function updateEngineConfig(config: NapiEngineConfigInput): void
/** Get engine status (group/trio counts, price slot count). */
export declare function getEngineStatus(): NapiEngineStatus
/**
 * Initialize the executor with trading configuration.
 *
 * Creates the signer (cached wallet), API client (persistent HTTP), and
 * spawns the executor loop. Must be called once at startup.
 */
export declare function initExecutor(config: NapiExecutorConfigInput): void
/** Register callback for trade results from executor. */
export declare function onTradeResult(callback: (result: TradeResult) => void): void
/** Update USDC balance (called by Node.js background refresh). */
export declare function updateBalance(usdcBalance: number): void
/** Enable/disable trading at runtime. */
export declare function setTradingEnabled(enabled: boolean): void
/**
 * Update minted asset balances for a group.
 *
 * Called by Node.js background refresh to push minted token amounts.
 * Used by executor to validate SELL leg sizes — can't sell more than minted.
 */
export declare function updateMintedAssets(groupKey: string, assets: Array<NapiMintedAssetEntry>): void
/** Minted asset entry input from Node.js. */
export interface NapiMintedAssetEntry {
  tokenId: string
  amount: number
}
/**
 * Place batch orders using Rust Core (signer + API client).
 *
 * This is the N-API entry point for the `place-batch-orders-rust` controller endpoint.
 * Reuses the executor's cached wallet for EIP-712 signing (HFT performance).
 * API credentials come from the `config` parameter (provided by JS service's credential cache)
 * rather than the executor's stored credentials which may be empty.
 *
 * Flow: Input orders → prepare OrderToSign[] → sign → HTTP POST → results
 */
export declare function placeBatchOrdersRust(config: NapiBatchOrderConfig, orders: Array<NapiBatchOrderInput>): NapiBatchOrderResult
/**
 * Configuration for the Rust socket engine.
 * Passed from Node.js via `initSocket()`.
 */
export interface SocketConfig {
  /** WebSocket URL (e.g. "wss://ws-subscriptions-clob.polymarket.com/ws/market") */
  wsUrl: string
  /** Maximum tokens per WebSocket connection (default: 50) */
  maxTokensPerConnection?: number
  /** Ping interval in milliseconds (default: 15000) */
  pingIntervalMs?: number
  /** Reconnection base delay in milliseconds (default: 1000) */
  reconnectBaseDelayMs?: number
  /** Maximum reconnection delay in milliseconds (default: 30000) */
  reconnectMaxDelayMs?: number
  /** Maximum reconnection attempts before giving up (default: unlimited = -1) */
  maxReconnectAttempts?: number
  /** Enable verbose tracing logs (default: false) */
  verbose?: boolean
}
/**
 * Top-of-book update emitted to Node.js callback.
 * Mirrors `TopOfBookUpdate` from `top-of-book.interface.ts`.
 */
export interface TopOfBookUpdate {
  assetId: string
  marketHash: string
  bestBid: number
  bestAsk: number
  bestBidSize?: number
  bestAskSize?: number
  lastPrice?: number
  timestampMs: number
}
/** Socket connection status exported to Node.js. */
export interface SocketStatus {
  totalConnections: number
  activeConnections: number
  subscribedTokens: number
  messagesReceived: number
  lastMessageAtMs?: number
}
/** Failed order detail — part of TradeResult. */
export interface NapiFailedOrder {
  tokenId: string
  side: string
  price: number
  errorMsg: string
}
/** Trade result — emitted to Node.js via on_trade_result callback. */
export interface TradeResult {
  success: boolean
  orderIds: Array<string>
  failedOrders: Array<NapiFailedOrder>
  totalCost: number
  expectedPnl: number
  latencyUs: number
  signalGroupKey: string
  signalStrategy: string
  signalProfitAbs: number
  signalProfitBps: number
  signalTimestampMs: number
}
/** Executor config input from Node.js (init_executor / update_executor_config). */
export interface NapiExecutorConfigInput {
  privateKey: string
  proxyAddress: string
  signerAddress: string
  apiKey: string
  apiSecret: string
  apiPassphrase: string
  clobUrl?: string
  minPnlThresholdPercent: number
  defaultSize: number
  slippageEnabled: boolean
  opportunityTimeoutMs?: number
}
/** Input order from Node.js for the manual place-batch-orders-rust API. */
export interface NapiBatchOrderInput {
  tokenId: string
  price: number
  size: number
  side: string
  feeRateBps?: number
  negRisk?: boolean
  orderType?: string
}
/** Single order result from the batch API. */
export interface NapiBatchOrderResultItem {
  success: boolean
  orderId?: string
  status?: string
  errorMsg?: string
}
/** Batch order result from the manual place-batch-orders-rust API. */
export interface NapiBatchOrderResult {
  success: boolean
  results: Array<NapiBatchOrderResultItem>
  error?: string
  latencyMs: number
}
/**
 * API credentials + config for the batch order API.
 * Passed from Node.js because the executor's stored credentials may be empty
 * (the JS service dynamically creates them via createOrDeriveApiKey).
 */
export interface NapiBatchOrderConfig {
  apiKey: string
  apiSecret: string
  apiPassphrase: string
  signerAddress: string
  clobUrl?: string
}
/**
 * Arbitrage signal emitted to Node.js via callback.
 *
 * Flat layout for optimal N-API serialization.
 * Contains all fields needed by `RealExecutionService.buildOrderCandidates()`
 * and `calculateTotalCost()`.
 */
export interface ArbSignal {
  groupKey: string
  eventSlug: string
  crypto: string
  strategy: string
  profitAbs: number
  profitBps: number
  timestampMs: number
  parentAssetId: string
  parentMarketSlug: string
  parentBestBid?: number
  parentBestAsk?: number
  parentBestBidSize?: number
  parentBestAskSize?: number
  parentNegRisk: boolean
  parentUpperAssetId: string
  parentUpperMarketSlug: string
  parentUpperBestBid?: number
  parentUpperBestAsk?: number
  parentUpperBestBidSize?: number
  parentUpperBestAskSize?: number
  parentUpperNegRisk: boolean
  childAssetId: string
  childMarketSlug: string
  childBestBid?: number
  childBestAsk?: number
  childBestBidSize?: number
  childBestAskSize?: number
  childNegRisk: boolean
  childIndex: number
  childrenSumAsk: number
  childrenSumBid: number
  parentBestBidFlat?: number
  parentBestAskFlat?: number
  parentUpperBestBidFlat?: number
  parentUpperBestAskFlat?: number
  triangleTotalCost?: number
  triangleTotalBid?: number
  trianglePayout?: number
  triangleMode?: string
  reason: string
}
