/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Input options for signing a CLOB order */
export interface SignOpts {
  /** Private key in hex format (with or without 0x prefix) */
  privateKey: string
  /** Random salt for the order */
  salt: string
  /** Maker address (proxy wallet) */
  maker: string
  /** Signer address (EOA) */
  signer: string
  /** Taker address (usually 0x0) */
  taker: string
  /** Token ID (position token) */
  tokenId: string
  /** Maker amount in USDC units (string to handle large numbers) */
  makerAmount: string
  /** Taker amount in token units (string to handle large numbers) */
  takerAmount: string
  /** Expiration timestamp (0 for no expiration) */
  expiration: string
  /** Order nonce */
  nonce: string
  /** Fee rate in basis points */
  feeRateBps: string
  /** Side: 0 = Buy, 1 = Sell */
  side: number
  /** Signature type: 2 = POLY_GNOSIS_SAFE */
  signatureType: number
  /** Whether this is a negRisk market (uses different exchange contract) */
  negRisk?: boolean
}
/** Signed order output */
export interface SignedOrder {
  /** Salt */
  salt: string
  /** Maker address */
  maker: string
  /** Signer address */
  signer: string
  /** Taker address */
  taker: string
  /** Token ID */
  tokenId: string
  /** Maker amount */
  makerAmount: string
  /** Taker amount */
  takerAmount: string
  /** Expiration */
  expiration: string
  /** Nonce */
  nonce: string
  /** Fee rate bps */
  feeRateBps: string
  /** Side */
  side: number
  /** Signature type */
  signatureType: number
  /** EIP-712 signature (hex encoded with 0x prefix) */
  signature: string
}
/**
 * Sign a CLOB order using EIP-712
 *
 * This function takes order parameters and a private key, computes the EIP-712
 * typed data hash, signs it, and returns the complete signed order.
 */
export declare function signClobOrder(opts: SignOpts): SignedOrder
/** Order parameters for batch signing (excludes private key) */
export interface OrderParams {
  /** Random salt for the order */
  salt: string
  /** Maker address (proxy wallet) */
  maker: string
  /** Signer address (EOA) */
  signer: string
  /** Taker address (usually 0x0) */
  taker: string
  /** Token ID (position token) */
  tokenId: string
  /** Maker amount in USDC units */
  makerAmount: string
  /** Taker amount in token units */
  takerAmount: string
  /** Expiration timestamp */
  expiration: string
  /** Order nonce */
  nonce: string
  /** Fee rate in basis points */
  feeRateBps: string
  /** Side: 0 = Buy, 1 = Sell */
  side: number
  /** Signature type: 2 = POLY_GNOSIS_SAFE */
  signatureType: number
  /** Whether this is a negRisk market */
  negRisk?: boolean
}
/**
 * Batch sign multiple orders using a single private key
 * Optimized to create the wallet instance only once
 */
export declare function signClobOrdersBatch(privateKey: string, orders: Array<OrderParams>): Array<SignedOrder>
